### ISSUE TITLE
WPFMouse.GetState().ScrollWheelValue wrong

### ISSUE THREAD

**Issue by Skeatwin** [ShyroFR/MonoGame.Interop#1]
Usually, this property take the value of the mouse scroll wheel by incrementing or decrementing the  scroll wheel step value (that setting into the OS, default is 120). So the corrects values for this property are all multiple of step value (ex: ..., -120, 0, 120, 240, ...). For more informations, see the official doc https://msdn.microsoft.com/fr-FR/library/microsoft.xna.framework.input.mousestate.scrollwheelvalue(v=xnagamestudio.40).aspx#Anchor_2

But here, the property return only -120, 0 and 120, that incorrect.

**Comment by ShyroFR** [comment]
The problem has been fixed on this commit: https://github.com/ShyroFR/MonoGame.Interop/commit/056f17d8a2ac1f8750ce18f915c55dbaece61572
